language: node_js
node_js:
  - "6"
  - "4"
  - "0.12"
  - "0.10"
notifications:
  irc:
    channels:
      - "chat.freenode.net#wikimedia-dev"
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} %{author}): %{message} - %{build_url}"
